# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set Environment variables
        run: |
          echo "TRAVIS_COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "github.ref ${{ github.ref }}"
          echo "github.event ${{ github.event }}"
          echo "github.head_ref ${{ github.head_ref }}"
          echo "GITHUB_EVENT_NAME $GITHUB_EVENT_NAME"
          echo "github.event_name ${{ github.event_name }}"
          echo "TRAVIS_BRANCH=$(echo ${{ github.ref }} | sed 's@refs/heads/@@' )" >> $GITHUB_ENV
          echo "TRAVIS_PULL_REQUEST=$(echo ${{ github.event_name }} | sed s/pull_request/true/ | grep true || echo false)" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -s && ./gradlew ciPerformRelease
